README.md, Sources/Entities/CredentialOffer/CredentialOfferRequest.swift, Sources/Entities/CredentialOffer/CredentialOfferRequestObject.swift, Sources/Entities/Encryption/BindingKey.swift, Sources/Entities/Errors/GenericErrorResponse.swift, Sources/Entities/IssuanceAuthorization.swift, Sources/Entities/Response/AccessTokenRequestResponse.swift, Sources/Entities/Types/ClaimSet.swift, Sources/Entities/Types/Grants.swift, Sources/Entities/Types/GrantsDTO.swift, Sources/Entities/Types/Types.swift, Sources/Issuers/Issuer.swift, Sources/Main/Authorisers/IssuanceAuthorizer.swift, Sources/Resources/europa/credential_offer_with_blank_pre_authorized_code.json, Sources/Resources/europa/jwt_vc_json_credential_offer.json, Sources/Resources/europa/sample_credential_offer.json, Sources/Resources/responses/access_token_request_response.json, Sources/Utilities/Constants.swift, Tests/Constants/TestsConstants.swift, Tests/Issuance/IssuanceAuthorizationTest.swift, Tests/Issuance/IssuanceSingleRequestTest.swift, Tests/Mocks/NetworkingThrowingMock.swift, Tests/Offer/CredentialOfferRequestTest.swift
Please include a summary of the change and what is fixed or updated. 
Please also include relevant motivation and context. 
List any dependencies that are required for this change.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
=> Updates related to pre-authorisation flow

Tests/Helpers/Wallet.swift, Tests/Wallet/VCIFlowNoOffer.swift, Tests/Wallet/VCIFlowWithOffer.swift
Please include a summary of the change and what is fixed or updated. 
Please also include relevant motivation and context. 
List any dependencies that are required for this change.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
=> Claims use case in wallet example

Package.swift, Sources/Entities/CredentialIssuer/CredentialIssuerMetadata.swift, Sources/Entities/CredentialSupported/CredentialSupported.swift, Sources/Entities/Issuance/SubmittedRequest.swift, Sources/Entities/IssuanceFlows/CredentialIssuanceRequest.swift, Tests/Constants/TestsConstants.swift, Tests/Helpers/Wallet.swift, Tests/Issuance/IssuanceAuthorizationTest.swift, Tests/Wallet/VCIFlowNoOffer.swift, Tests/Wallet/VCIFlowWithOffer.swift
Please include a summary of the change and what is fixed or updated. 
Please also include relevant motivation and context. 
List any dependencies that are required for this change.
=> Draft 13 - Minor updates

Sources/Main/Authorisers/IssuanceAuthorizer.swift
=> [fix] authorization endpoint parse fix

Sources/Main/Resolvers/CredentialOffer/AuthorizationServerMetadataResolver.swift, Tests/Utilities/URLModifierTests.swift
=> Auth servers proper resolution

Sources/DPoP/DPoPConstructor.swift, Sources/Entities/AuthorizationToken.swift, Sources/Entities/Encryption/BindingKey.swift, Sources/Entities/Issuance/AuthorizedRequest.swift, Sources/Entities/IssuanceAccessToken.swift, Sources/Entities/IssuanceFlows/CredentialIssuanceRequest.swift, Sources/Entities/IssuanceRefreshToken.swift, Sources/Entities/Profiles/MsoMdocFormat.swift, Sources/Entities/Profiles/SdJwtVcFormat.swift, Sources/Entities/Response/AccessTokenRequestResponse.swift, Sources/Entities/Types/JWTClaimNames.swift, Sources/Entities/Types/Types.swift, Sources/Issuers/IssuanceRequester.swift, Sources/Issuers/Issuer.swift, Sources/Main/Authorisers/AuthorizationServerClient.swift, Tests/Helpers/Wallet.swift, Tests/Issuance/IssuanceAuthorizationTest.swift, Tests/Issuance/IssuanceBatchRequestTest.swift, Tests/Issuance/IssuanceDeferredRequestTest.swift, Tests/Issuance/IssuanceNotificationTest.swift, Tests/Issuance/IssuanceSingleRequestTest.swift, Tests/Wallet/VCIFlowNoOffer.swift, Tests/Wallet/VCIFlowWithOffer.swift
=> Feature - DPoP support

Sources/Entities/Wallet/Config.swift, Sources/Issuers/Issuer.swift, Sources/Main/Resolvers/CredentialOffer/AuthorizationServerMetadataResolver.swift, Sources/Main/Resolvers/CredentialOffer/CredentialIssuerMetadataResolver.swift, Sources/Main/Resolvers/CredentialOffer/CredentialOfferRequestResolver.swift, Sources/Utilities/RemoteDataAccess/Fetcher.swift, Sources/Utilities/RemoteDataAccess/Poster.swift, Tests/Helpers/Wallet.swift, Tests/Issuance/IssuanceBatchRequestTest.swift
=> [fix] removed self signed

.gitignore
Ignore `.DS_Store` files from the Git repository. The files are commonly created by macOS and clutter local changes unless ignored.
Source control improvement.
N/A
N/A
=> [chore] Git ignore .DS_Store files

Sources/Entities/Encryption/BindingKey.swift
=> [fix] filter empty content in jwt

Sources/Issuers/IssuanceRequester.swift
Please include a summary of the change and what is fixed or updated. 
Please also include relevant motivation and context. 
List any dependencies that are required for this change.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
=> Fixed deferred issuance pending status

Package.resolved, Package.swift, Sources/DPoP/DPoPConstructor.swift, Sources/Entities/Encryption/BindingKey.swift, Sources/Entities/Errors/JOSEError.swift
Change JOSESwift dependency from forked https://github.com/niscy-eudiw/JOSESwift.git to the upstream https://github.com/airsidemobile/JOSESwift.git v0.3.0 or later minor version.
Dependency update and switch back to upstream version.
=> Switch to JOSESwift upstream version >=0.3.0

Sources/Entities/CredentialIssuer/CredentialIssuerId.swift, Sources/Entities/Errors/CredentialError.swift
Updated CredentialIssuerId "from: Decoder" constructor to use all validations.
Addresses #93 
=> Credential issuer id update

Sources/Entities/Encryption/BindingKey.swift, Tests/Constants/TestsConstants.swift, Tests/Wallet/VCIFlowWithOffer.swift
Updated async signer protocol to provide signature.
=> Async signer updates

.github/workflows/build-package.yml, Sources/Entities/Issuance/UnauthorizedRequest.swift, Sources/Issuers/Issuer.swift
Support dpop nonce during authorization
=> Dpop nonce support during authorization

Sources/Main/AttestationBasedClient/ClientAttestation.swift, Sources/Main/AttestationBasedClient/ClientAttestationPoPBuilder.swift, Sources/Main/AttestationBasedClient/ClientAttestationPoPJWTSpec.swift, Tests/Helpers/SelfSignedClientAttestation.swift
JWT updates related to client attestation
=> Client attestation updates

Sources/Issuers/Issuer.swift
If a code is numeric an error is not thrown
=> Numeric code is not error

Sources/Entities/Encryption/CredentialResponseEncryption.swift, Sources/Entities/Issuance/AuthorizedRequest.swift, Sources/Issuers/Issuer.swift, Sources/Utilities/RemoteDataAccess/Poster.swift, Tests/Helpers/Wallet.swift, fastlane/.xcovignore
New issuer initializer, refresh token fix, tiny updates
=> New issuer initializer, refresh token fix, tiny updates

Sources/Main/Authorisers/AuthorizationServerClient.swift
Dpop token creation takes URL into account.
=> Take url into account when creating dpop token.

Sources/Entities/Types/Display.swift
Addresses #136 
- [] I have commented my code, particularly in hard-to-understand areas
=> Metadata fix

Sources/Issuers/IssuanceRequester.swift
=> Decrypt fix with EC keys

Sources/Entities/IssuanceFlows/CredentialIssuanceRequest.swift
=> Removed additional fields

Sources/Issuers/Issuer.swift
=> IssuerType is now sendable

Sources/Entities/CredentialIssuer/ProofType.swift, Sources/Entities/CredentialSupported/CredentialSupported.swift, Sources/Entities/IssuanceFlows/CredentialIssuanceRequest.swift, Sources/Issuers/IssuanceRequester.swift
=> Proofs `alg` verification

Gemfile.lock, Sources/Entities/CredentialIssuer/ProofType.swift, Sources/Entities/CredentialSupported/CredentialSupported.swift, Sources/Entities/IssuanceFlows/CredentialIssuanceRequest.swift, Sources/Issuers/IssuanceRequester.swift, Sources/Issuers/Issuer.swift, Sources/Main/Authorisers/AuthorizationServerClient.swift, Sources/Main/Nonce/NonceEndpointClient.swift
=> Handle DPoP nonce returned from Nonce Endpoint
